USE [University_Родионов]
GO

/****** Object:  Table [dbo].[TEACHER]    Script Date: 12.02.2023 18:23:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TEACHER](
	[KOD_TEACHER] [int] NOT NULL,
	[KOD_KAFEDRU] [int] NULL,
	[NAME_TEACHER] [nvarchar](100) NULL,
	[INDEF_KOD] [int] NULL,
	[DOLGNOST] [nvarchar](50) NULL,
	[ZVANIE] [nvarchar](10) NULL,
	[SALARY] [money] NULL,
	[RISE] [money] NULL,
	[DATA_HIRE] [date] NULL,
	[BIRTHDAY] [date] NULL,
	[POL] [nvarchar](1) NULL,
	[TEL_TEACHER] [nvarchar](8) NULL,
 CONSTRAINT [PK_TEACHER] PRIMARY KEY CLUSTERED 
(
	[KOD_TEACHER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TEACHER]  WITH CHECK ADD FOREIGN KEY([KOD_KAFEDRU])
REFERENCES [dbo].[Kafedra] ([kod_kafedru])
GO

ALTER TABLE [dbo].[TEACHER]  WITH CHECK ADD  CONSTRAINT [CK_TEACHER_2] CHECK  (([SALARY]>(0)))
GO

ALTER TABLE [dbo].[TEACHER] CHECK CONSTRAINT [CK_TEACHER_2]
GO

ALTER TABLE [dbo].[TEACHER]  WITH CHECK ADD  CONSTRAINT [CK_TEACHER_3] CHECK  (([TEL_TEACHER] like '[1-9][0-9]-[0-9][0-9]-[0-9][0-9]'))
GO

ALTER TABLE [dbo].[TEACHER] CHECK CONSTRAINT [CK_TEACHER_3]
GO


